In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/Hyejeong

/content/drive/MyDrive/Hyejeong


In [3]:
import pandas as pd
from glob import glob
import numpy as np
np.set_printoptions(precision=6, suppress=True)

raw_dataset = np.loadtxt("HAND_09.csv", delimiter=",")
aug_dataset = raw_dataset

print(raw_dataset.shape) # (1600, 86)
print(raw_dataset)

for index_c, temp_row in enumerate(raw_dataset[:,:84]):
  for index_r, value in enumerate(temp_row):
    if (index_r % 2 == 0) and (value != 0) :
      aug_dataset[index_c, index_r] = value - 20

print(aug_dataset.shape)
print(aug_dataset)

(1600, 86)
[[1164.  865. 1173. ... 1027.    0.    9.]
 [1164.  865. 1168. ... 1030.    1.    9.]
 [1163.  867. 1170. ... 1047.    2.    9.]
 ...
 [1064.  893. 1042. ...  971.   17.    9.]
 [1063.  897. 1041. ...  982.   18.    9.]
 [1063.  897. 1040. ...  983.   19.    9.]]
(1600, 86)
[[1144.  865. 1153. ... 1027.    0.    9.]
 [1144.  865. 1148. ... 1030.    1.    9.]
 [1143.  867. 1150. ... 1047.    2.    9.]
 ...
 [1044.  893. 1022. ...  971.   17.    9.]
 [1043.  897. 1021. ...  982.   18.    9.]
 [1043.  897. 1020. ...  983.   19.    9.]]


In [4]:
df = pd.DataFrame(aug_dataset)
df.to_csv('HAND_09_Shift.csv', header=False, index=False) # csv파일로 저장